### ISSUE TITLE
[Bug] Plugin ownpad Crash Nextcloud 27.0.2 greater than 0.9.0

### ISSUE THREAD

**Issue by Alpha6333** [otetard/ownpad#131]
Since today we have installed the new plugin via the appstore on doe 0.9.4

As soon as I go into my Nextcloud home dir and there is a <name>.pad in it, some javascript loads in the infinite loop. The browser (Fireforx and Chrome) asks me if I want to stop the script.

Version below 0.9.0 can no longer open the pad files.

```
sudo -u www-data php8.2 /var/www/nextcloud2/occ status
  - installed: true
  - version: 27.0.2.1
  - versionstring: 27.0.2
  - edition:
  - maintenance: false
  - needsDbUpgrade: false
  - productname: Nextcloud
  - extendedSupport: false
  ```
